name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme mathjax sphinxcontrib-napoleon numpydoc ipython
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}

# name: Deploy Sphinx documentation to Pages

# on:
#   push:
#     branches: [master] # branch to trigger deployment
#   workflow_dispatch:  # This line adds the manual trigger option

# jobs:
#   pages:
#     runs-on: ubuntu-20.04
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     permissions:
#       pages: write
#       id-token: write
#     steps:
#     - name: Install dependencies
#       run: |
#         python -m pip install -U sphinx
#         python -m pip install sphinx-rtd-theme mathjax sphinxcontrib-napoleon numpydoc ipython

#     - id: deployment
#       uses: sphinx-notes/pages@v3 
#       with:
#         documentation_path: './docs/source'
 